Try to render book again

diff --git a/.github/workflows/render_book_on_pr.yml b/.github/workflows/render_book_on_pr.yml
--- a/.github/workflows/render_book_on_pr.yml
+++ b/.github/workflows/render_book_on_pr.yml
@@ -54,7 +54,12 @@ jobs:
 
 
       - name: Render the book
-        run: Rscript -e 'babelquarto::render_book()'
+        run: |
+          Rscript -e 'babelquarto::render_book()' || {
+            echo "Rendering the book failed. Displaying session info for debugging.";
+            Rscript -e 'sessionInfo()';
+            exit 1;
+          }
 
       - name: Commit results to main branch
         run: |
